columnSuffix: null
contentColumnType: string
fieldGroup: f348b0c6-b79b-4197-b9b4-054934d817f6 # Commerce
handle: shopBrand
instructions: ''
name: Brand
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: '1'
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:caf3284e-dc22-4e85-8335-117381fd7bb2' # Shop Brands
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
