defaultPlacement: end
fieldLayouts:
  4dc14f93-406c-42a2-a4ff-cb96a44c79b1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: shopVariants
name: 'Shop Variants'
siteSettings:
  06fb793a-57ef-483e-8415-675d2cfa2fd8: # Craft 3
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: bc96e77e-8829-4db9-b239-45f6e2e9f3c7
