defaultPlacement: end
fieldLayouts:
  321f6239-c5c5-4f56-940d-897200483d9a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: shopBrands
name: 'Shop Brands'
siteSettings:
  06fb793a-57ef-483e-8415-675d2cfa2fd8: # Craft 3
    hasUrls: true
    template: commerce/_category
    uriFormat: '{parent.uri ? parent.uri : commerce.shopPath}/{slug}'
structure:
  maxLevels: null
  uid: 1bf60511-96fc-4150-9e6d-969056f56769
