fieldLayouts:
  4765e0ca-6d7f-4713-8485-95d54d1b475e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: shop
hasUrls: true
name: Shop
settings:
  path: '@assetBasePath/shop'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\volumes\Local
url: '@assetBaseUrl/shop'
