<?php

namespace mythdigital\mythcommerce\models;

/**
 * Represents a customer address.
 * @SWG\Definition(title="CommerceAddress")
 *
 * @SWG\Property(property="id", type="string")
 * @SWG\Property(property="isStoreLocation", type="boolean")
 * @SWG\Property(property="attention", type="string")
 * @SWG\Property(property="title", type="string")
 * @SWG\Property(property="firstName", type="string")
 * @SWG\Property(property="lastName", type="string")
 * @SWG\Property(property="fullName", type="string")
 * @SWG\Property(property="address1", type="string")
 * @SWG\Property(property="address2", type="string")
 * @SWG\Property(property="address3", type="string")
 * @SWG\Property(property="city", type="string")
 * @SWG\Property(property="zipCode", type="string")
 * @SWG\Property(property="phone", type="string")
 * @SWG\Property(property="alternativePhone", type="string")
 * @SWG\Property(property="label", type="string")
 * @SWG\Property(property="businessName", type="string")
 * @SWG\Property(property="businessTaxId", type="string")
 * @SWG\Property(property="businessId", type="string")
 * @SWG\Property(property="stateName", type="string")
 * @SWG\Property(property="countryId", type="string")
 * @SWG\Property(property="stateId", type="string")
 * @SWG\Property(property="notes", type="string")
 * @SWG\Property(property="custom1", type="string")
 * @SWG\Property(property="custom2", type="string")
 * @SWG\Property(property="custom3", type="string")
 * @SWG\Property(property="custom4", type="string")
 * @SWG\Property(property="isEstimated", type="string")
 * @SWG\Property(property="stateValue", type="string")
 * @SWG\Property(property="countryIso", type="string")
 * @SWG\Property(property="countryText", type="string")
 * @SWG\Property(property="stateText", type="string")
 * @SWG\Property(property="abbreviationText", type="string")
 * @SWG\Property(property="addressLines", type="array", @SWG\Items(type="string"))
 */
class CommerceAddress {}

/**
 * Represents a customer address to be stored.
 * @SWG\Definition(title="StoreCommerceAddress")
 *
 * @SWG\Property(property="makePrimaryBillingAddress", type="boolean")
 * @SWG\Property(property="makePrimaryShippingAddress", type="boolean")
 * @SWG\Property(property="success", type="boolean")
 * @SWG\Property(property="address", ref="#/definitions/CommerceAddress")
 */
class StoreCommerceAddress {}

/**
 * Represents a customer order.
 * 
 * @SWG\Definition(title="CommerceOrder")
 *
 * @SWG\Property(property="number", type="string")
 * @SWG\Property(property="reference", type="string")
 * @SWG\Property(property="couponCode", type="string")
 * @SWG\Property(property="isCompleted", type="string")
 * @SWG\Property(property="dateOrdered", type="string")
 * @SWG\Property(property="datePaid", type="string")
 * @SWG\Property(property="dateAuthorized", type="string")
 * @SWG\Property(property="currency", type="string")
 * @SWG\Property(property="gatewayId", type="string")
 * @SWG\Property(property="lastIp", type="string")
 * @SWG\Property(property="message", type="string")
 * @SWG\Property(property="returnUrl", type="string")
 * @SWG\Property(property="cancelUrl", type="string")
 * @SWG\Property(property="orderStatusId", type="string")
 * @SWG\Property(property="orderLanguage", type="string")
 * @SWG\Property(property="orderSiteId", type="string")
 * @SWG\Property(property="origin", type="string")
 * @SWG\Property(property="billingAddressId", type="string")
 * @SWG\Property(property="shippingAddressId", type="string")
 * @SWG\Property(property="makePrimaryShippingAddress", type="string")
 * @SWG\Property(property="makePrimaryBillingAddress", type="string")
 * @SWG\Property(property="shippingSameAsBilling", type="string")
 * @SWG\Property(property="billingSameAsShipping", type="string")
 * @SWG\Property(property="estimatedBillingAddressId", type="string")
 * @SWG\Property(property="estimatedShippingAddressId", type="string")
 * @SWG\Property(property="estimatedBillingSameAsShipping", type="string")
 * @SWG\Property(property="shippingMethodHandle", type="string")
 * @SWG\Property(property="shippingMethodName", type="string")
 * @SWG\Property(property="customerId", type="string")
 * @SWG\Property(property="registerUserOnOrderComplete", type="string")
 * @SWG\Property(property="paymentSourceId", type="string")
 * @SWG\Property(property="storedTotalPrice", type="string")
 * @SWG\Property(property="storedTotalPaid", type="string")
 * @SWG\Property(property="storedItemTotal", type="string")
 * @SWG\Property(property="storedItemSubtotal", type="string")
 * @SWG\Property(property="storedTotalShippingCost", type="string")
 * @SWG\Property(property="storedTotalDiscount", type="string")
 * @SWG\Property(property="storedTotalTax", type="string")
 * @SWG\Property(property="storedTotalTaxIncluded", type="string")
 * @SWG\Property(property="id", type="integer")
 * @SWG\Property(property="tempId", type="integer")
 * @SWG\Property(property="draftId", type="integer")
 * @SWG\Property(property="revisionId", type="string")
 * @SWG\Property(property="uid", type="string")
 * @SWG\Property(property="siteSettingsId", type="integer")
 * @SWG\Property(property="fieldLayoutId", type="integer")
 * @SWG\Property(property="contentId", type="integer")
 * @SWG\Property(property="enabled", type="boolean")
 * @SWG\Property(property="archived", type="boolean")
 * @SWG\Property(property="siteId", type="integer")
 * @SWG\Property(property="title", type="string")
 * @SWG\Property(property="slug", type="string")
 * @SWG\Property(property="uri", type="string")
 * @SWG\Property(property="dateCreated", type="string")
 * @SWG\Property(property="dateUpdated", type="string")
 * @SWG\Property(property="dateDeleted", type="string")
 * @SWG\Property(property="trashed", type="boolean")
 * @SWG\Property(property="propagateAll", type="boolean")
 * @SWG\Property(property="newSiteIds", type="array", @SWG\Items(type="string"))
 * @SWG\Property(property="resaving", type="boolean")
 * @SWG\Property(property="duplicateOf", type="string")
 * @SWG\Property(property="previewing", type="boolean")
 * @SWG\Property(property="hardDelete", type="boolean")
 * @SWG\Property(property="ref", type="string")
 * @SWG\Property(property="status", type="string")
 * @SWG\Property(property="structureId", type="string")
 * @SWG\Property(property="url", type="string")
 * @SWG\Property(property="orderType", type="string")
 * @SWG\Property(property="adjustmentSubtotal", type="number")
 * @SWG\Property(property="adjustmentsTotal", type="number")
 * @SWG\Property(property="paymentCurrency", type="string")
 * @SWG\Property(property="email", type="string")
 * @SWG\Property(property="isPaid", type="boolean")
 * @SWG\Property(property="itemSubtotal", type="number")
 * @SWG\Property(property="itemTotal", type="number")
 * @SWG\Property(property="lineItems", type="array", @SWG\Items(ref = "#/definitions/CommerceOrderLineItem"))
 * @SWG\Property(property="outstandingBalance", type="number")
 * @SWG\Property(property="paidStatus", type="string")
 * @SWG\Property(property="recalculationMode", type="string")
 * @SWG\Property(property="shortNumber", type="string")
 * @SWG\Property(property="totalPaid", type="number")
 * @SWG\Property(property="total", type="number")
 * @SWG\Property(property="totalPrice", type="number")
 * @SWG\Property(property="totalQty", type="integer")
 * @SWG\Property(property="totalSaleAmount", type="number")
 * @SWG\Property(property="totalTaxablePrice", type="number")
 * @SWG\Property(property="totalWeight", type="number")
 * @SWG\Property(property="adjustmentSubtotalAsCurrency", type="string")
 * @SWG\Property(property="adjustmentsTotalAsCurrency", type="string")
 * @SWG\Property(property="itemSubtotalAsCurrency", type="string")
 * @SWG\Property(property="itemTotalAsCurrency", type="string")
 * @SWG\Property(property="outstandingBalanceAsCurrency", type="string")
 * @SWG\Property(property="totalPaidAsCurrency", type="string")
 * @SWG\Property(property="totalAsCurrency", type="string")
 * @SWG\Property(property="totalPriceAsCurrency", type="string")
 * @SWG\Property(property="totalSaleAmountAsCurrency", type="string")
 * @SWG\Property(property="totalTaxablePriceAsCurrency", type="string")
 * @SWG\Property(property="totalTaxAsCurrency", type="string")
 * @SWG\Property(property="totalTaxIncludedAsCurrency", type="string")
 * @SWG\Property(property="totalShippingCostAsCurrency", type="string")
 * @SWG\Property(property="totalDiscountAsCurrency", type="string")
 * @SWG\Property(property="storedTotalPriceAsCurrency", type="string")
 * @SWG\Property(property="storedTotalPaidAsCurrency", type="string")
 * @SWG\Property(property="storedItemTotalAsCurrency", type="string")
 * @SWG\Property(property="storedItemSubtotalAsCurrency", type="string")
 * @SWG\Property(property="storedTotalShippingCostAsCurrency", type="string")
 * @SWG\Property(property="storedTotalDiscountAsCurrency", type="string")
 * @SWG\Property(property="storedTotalTaxAsCurrency", type="string")
 * @SWG\Property(property="storedTotalTaxIncludedAsCurrency", type="string")
 * @SWG\Property(property="paidStatusHtml", type="string")
 * @SWG\Property(property="customerLinkHtml", type="string")
 * @SWG\Property(property="orderStatusHtml", type="string")
 * @SWG\Property(property="totalTax", type="number")
 * @SWG\Property(property="totalTaxIncluded", type="number")
 * @SWG\Property(property="totalShippingCost", type="number")
 * @SWG\Property(property="totalDiscount", type="number")
 * @SWG\Property(property="orderStatus", type="string")
 * @SWG\Property(property="orderStatusDisplayLabel", type="string")
 * @SWG\Property(property="statusHistory", type="array", @SWG\Items(ref = "#/definitions/OrderStatusHistory"))
 */
class CommerceOrder {}

/**
 * Represents a customer order after submitting changes.
 * 
 * @SWG\Definition(title="CommerceOrderResponse")
 * @SWG\Property(property="error", type="string")
 * @SWG\Property(property="errors", type="object")
 * @SWG\Property(property="success", type="boolean")
 * @SWG\Property(property="message", type="string")
 * @SWG\Property(property="cart", ref = "#/definitions/CommerceOrder")
 */
class CommerceOrderResponse {}

/**
 * Represents an order adjustment.
 * @SWG\Definition(title="CommerceOrderAdjustment")
 *
 * @SWG\Property(property="id", type="integer")
 * @SWG\Property(property="name", type="string")
 * @SWG\Property(property="description", type="string")
 * @SWG\Property(property="type", type="string")
 * @SWG\Property(property="amount", type="number")
 * @SWG\Property(property="included", type="boolean")
 * @SWG\Property(property="orderId", type="integer")
 * @SWG\Property(property="lineItemId", type="integer")
 * @SWG\Property(property="isEstimated", type="boolean")
 * @SWG\Property(property="sourceSnapshot", type="object")
 * @SWG\Property(property="amountAsCurrency", type="string")
 */
class CommerceOrderAdjustment {}

/**
 * Represents an order line item.
 * @SWG\Definition(title="CommerceOrderLineItem")
 *
 * @SWG\Property(property="id", type="integer")
 * @SWG\Property(property="weight", type="number")
 * @SWG\Property(property="length", type="number")
 * @SWG\Property(property="height", type="number")
 * @SWG\Property(property="width", type="number")
 * @SWG\Property(property="qty", type="integer")
 * @SWG\Property(property="note", type="string")
 * @SWG\Property(property="privateNote", type="string")
 * @SWG\Property(property="purchasableId", type="integer")
 * @SWG\Property(property="orderId", type="integer")
 * @SWG\Property(property="lineItemStatusId", type="integer")
 * @SWG\Property(property="taxCategoryId", type="integer")
 * @SWG\Property(property="shippingCategoryId", type="integer")
 * @SWG\Property(property="dateCreated", type="string")
 * @SWG\Property(property="dateUpdated", type="string")
 * @SWG\Property(property="adjustments", type="array", @SWG\Items(ref = "#/definitions/CommerceOrderAdjustment"))
 * @SWG\Property(property="description", type="string")
 * @SWG\Property(property="options", type="object")
 * @SWG\Property(property="optionsSignature", type="string")
 * @SWG\Property(property="onSale", type="boolean")
 * @SWG\Property(property="price", type="number")
 * @SWG\Property(property="saleAmount", type="number")
 * @SWG\Property(property="salePrice", type="number")
 * @SWG\Property(property="sku", type="string")
 * @SWG\Property(property="total", type="number")
 * @SWG\Property(property="priceAsCurrency", type="string")
 * @SWG\Property(property="saleAmountAsCurrency", type="string")
 * @SWG\Property(property="salePriceAsCurrency", type="string")
 * @SWG\Property(property="subtotalAsCurrency", type="string")
 * @SWG\Property(property="totalAsCurrency", type="string")
 * @SWG\Property(property="discountAsCurrency", type="string")
 * @SWG\Property(property="shippingCostAsCurrency", type="string")
 * @SWG\Property(property="taxAsCurrency", type="string")
 * @SWG\Property(property="taxIncludedAsCurrency", type="string")
 * @SWG\Property(property="adjustmentsTotalAsCurrency", type="string")
 * @SWG\Property(property="subtotal", type="number")
 */
class CommerceOrderLineItem {}

/**
 * Represents a payment source to be added.
 * @SWG\Definition(title="CommerceAddPaymentSource")
 *
 * @SWG\Property(property="token", type="string")
 * @SWG\Property(property="tokenType", type="string")
 * @SWG\Property(property="expiryDate", type="string")
 * @SWG\Property(property="cardHolderName", type="string")
 * @SWG\Property(property="nickname", type="string")
 * @SWG\Property(property="savePaymentSource", type="boolean")
 * @SWG\Property(property="defaultCard", type="boolean")
 */
class CommerceAddPaymentSource {}

/**
 * Represents a payment source to be deleted.
 * @SWG\Definition(title="CommerceDeletePaymentSource")
 *
 * @SWG\Property(property="id", type="string")
 */
class CommerceDeletePaymentSource {}